Add a django command to set up the demo data
multinet-app/multinet-api pull request #133
Opened 2022-06-15 16:52 UTC by JackWilb

### Does this PR close any open issues?
Depends on #132 
Closes #19

### Give a longer description of what this PR addresses and why it's needed
This PR adds all the demo data into an instance of multinet from the command line. This gives us a standardized set of networks that can be set up on any multinet instance. I made all the workspaces public so it should be accessible from any client application without authentication.

### Provide pictures/videos of the behavior before and after these changes (optional)
![image](https://user-images.githubusercontent.com/36867477/173882705-e3f640d1-bdda-4c9d-a58a-431925df83c3.png)

### Are there any additional TODOs before this PR is ready to go?

TODOs:
- [ ] Fix TODO in code, adding table column types

2022-06-22 17:11 UTC, AlmightyYakob commented
What is the point of all the fetchdata / process scripts? Why not just check the "processed" data itself into the repo?

2022-06-23 19:29 UTC, AlmightyYakob requested changes
Looks good overall, just some code suggestions.

2022-06-23 19:29 UTC, AlmightyYakob commented on multinet/api/management/commands/setupdevenv.py
> +                filename = str(csv_path).split("/")[-1].split(".")[0]
A more idiomatic way to do this

```suggestion
                filename = os.path.splitext(csv_path.name)[0]
```

2022-06-23 19:29 UTC, AlmightyYakob commented on multinet/api/management/commands/setupdevenv.py
> +                types_path = Path(str(csv_path).replace(f"{filename}.csv", "")) / "types" / f"{filename}.json"
```suggestion
                types_path = data_dir_path / "types" / f"{filename}.json"
```

2022-06-23 19:29 UTC, AlmightyYakob commented on multinet/api/management/commands/setupdevenv.py
> +        self.user = queried_users.first()
```suggestion
        self.user = User.objects.filter(email=options["email"]).first()
        if self.user is None:
      	    raise Exception('User did not exist')        
```

2022-06-23 19:29 UTC, AlmightyYakob commented on multinet/api/management/commands/setupdevenv.py
> +        self.create_network_in_workspace("openflights", "routes", ["airports"])
```suggestion
        # Create the tables
        self.create_tables_for_workspace("boston", "membership")
        self.create_tables_for_workspace("eurovis-2019", "connections")
        self.create_tables_for_workspace("miserables", "relationships")
        self.create_tables_for_workspace("openflights", "routes")

        # Create the networks from the tables
        self.create_network_in_workspace("boston", "membership", ["clubs", "members"])
        self.create_network_in_workspace("eurovis-2019", "connections", ["people"])
        self.create_network_in_workspace("miserables", "relationships", ["characters"])
        self.create_network_in_workspace("openflights", "routes", ["airports"])
        
        # TODO: Include movies dataset here once new network creation API is accessible internally from the API
```

2022-06-24 16:54 UTC, AlmightyYakob commented
@JackWilb can we also remove all of the `scripts` folders? If keeping track of the data source is important, I'd think we could just put some kind of `README` in the `data` folder to illustrate that. My main gripe with what's there now is that there's lots of these `script` folders, with no explanation of why they're there / what role they play in the system.

2022-06-26 23:52 UTC, JackWilb commented
> @JackWilb can we also remove all of the `scripts` folders? If keeping track of the data source is important, I'd think we could just put some kind of `README` in the `data` folder to illustrate that. My main gripe with what's there now is that there's lots of these `script` folders, with no explanation of why they're there / what role they play in the system.

Roni and I discussed this a little on slack. The scripts are good for showing a user how to transform data from a raw format to one that will work with our csv uploaders. I think that removing them entirely would remove some value that we get from them. Do you think it's okay to keep them here and link to them from the docs, or should we consider moving them to another place?

2022-06-27 21:11 UTC, JackWilb commented
Force pushed to rebase on #132 updates, which will also need a review before this can be merged

2022-06-28 15:58 UTC, AlmightyYakob approved these changes

2022-06-28 22:26 UTC, merged